# Alacritty configuration file

[window]

opacity = 0.92
blur = true
dimensions = { columns = 80, lines = 20 }
decorations = "Transparent"
position = "None"

[font]

normal = { family = "Noto Sans Mono", style = "Bold"}
size = 12.3

[cursor]

style = { shape = "Underline", blinking = "On" }
blink_interval = 900

[terminal]

shell = "/bin/bash"
#shell = "/bin/fish"
