# Alacritty configuration file

[window]

opacity = 0.8
blur = true
dimensions = { columns = 80, lines = 15 }
decorations = "Transparent"
position = "None"

[cursor]

style = { shape = "Beam", blinking = "On" }
blink_interval = 900

[terminal]

shell = "/bin/fish"
